directories:
  output: release-demo
  buildResources: build
appId: com.edefter.klasorotomasyon.demo
productName: E-Defter Otomasyon DEMO
compression: store
files:
  - filter:
      - dist/**/*
      - electron/main-demo.cjs
      - electron/preload.cjs
      - electron/trial-checker.cjs
      - node_modules/**/*
      - package.json
extraResources:
  - from: assets
    to: assets
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: icon.ico
  artifactName: ${productName} Setup ${version}.${ext}
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  installerIcon: icon.ico
  uninstallerIcon: icon.ico
  installerHeaderIcon: icon.ico
  deleteAppDataOnUninstall: false
  shortcutName: E-Defter Otomasyon DEMO
  differentialPackage: false
publish: null
electronVersion: 38.7.2
